spring:
  application:
    name: xoj-gateway-service
  cloud:
    nacos:
      discovery:
        port: 8848
        server-addr: 192.168.247.139
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration