spring:
  application:
    name: xoj-user-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pipi_xoj_user?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      database: 1
      host: 192.168.247.139
      port: 6379
      connect-timeout: 10s
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.139:8848
server:
  port: 31505
  servlet:
    context-path: /api/xoj/v1

seata:
  tx-service-group: xoj-seata-server
  service:
    vgroup-mapping:
      xoj-seata-server: default
    grouplist:
      default: 192.168.247.139:8091
