spring:
  application:
    name: xoj-problem-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pipi_xoj_problem?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.139:8848
server:
  port: 31506
  servlet:
    context-path: /api/xoj/v1